START  = <WHITESPACE?> EXPR <WHITESPACE?>
<EXPR> = GROUP | SUM | DIFF
<GROUP> = PRECEDENCE | NUMBER | <'('> <WHITESPACE?> EXPR <WHITESPACE?>  <')'>
<PRECEDENCE> = PROD | DIV
SUM = EXPR <WHITESPACE?> <'+'> <WHITESPACE?> GROUP
DIFF = EXPR <WHITESPACE?> <'-'> <WHITESPACE?> GROUP
PROD = EXPR <WHITESPACE?> <'*'> <WHITESPACE?> GROUP
DIV = EXPR <WHITESPACE?> <'/'> <WHITESPACE?> GROUP
NUMBER = #'[-+]?[0-9]+'
WHITESPACE = #'[,\ \t]+'
